### ISSUE TITLE
Any chance you want to rename it to not cause confusion with ansible.com?

### ISSUE THREAD

**Issue by pdebruic** [ba-st/Ansible#23]
ansible.com is an open source server orchestration/automation product from redhat.  Like Puppet &  Chef.  

https://docs.ansible.com/#project

**Comment by fortizpenaloza** [comment]
Hello @pdebruic, we knew about Redhat's ansible, but after discussing it for a while, we agreed it was a great name for it!

Being a small project within a tight community, we assessed that the probability of confusion would be zero. We're open to change it, did we miss something in our evaluation?

Thanks!

**Comment by pdebruic** [comment]
🤷‍♂️


Primarily, aesthetically it seems like there are enough words in the world to give a thing its own name.  



But I would guess the US trademark holders for the term won't mind because it won't be confusing to a layperson that you're not really doing the same thing and they won't have to pressure you to stop using their term if/once they discover your use of it on their own. See these records:


http://tmsearch.uspto.gov/bin/showfield?f=toc&state=4803%3A36daug.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_tagrepl%7E%3A=PARA1%24LD&expr=PARA1+AND+PARA2&p_s_PARA2=ansible&p_tagrepl%7E%3A=PARA2%24COMB&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query



And this overview: https://en.wikipedia.org/wiki/United_States_trademark_law

I think because its on github that makes it US jurisdiction too.  

But IANAL and may be wrong about all of the above. 

What did your evaluation come up with about the trademark issue?

**Comment by pdebruic** [comment]
And to be clear I don't care what you name it just thought I'd raise the issue that you named it the same as something else in the event you didn't know.

**Comment by gcotelli** [comment]
We take a look at the trademark and we think the scope of this project is different to the trademarked one, and that no confusion with Ansible, the provisioning platform is possible. It's a tiny open source project, Smalltalk related specifically with no intention of expanding from this scope.

We're trying to keep a metaphor regarding all the network service projects naming them in the spirit of space-related sci-fi things. And the inspiration for this one is https://en.wikipedia.org/wiki/Ansible.
